language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - redis
before_install:
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rake
