# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e753570c21a8e03b31b5fad6f7c5fbfe2f60f0124997d7611f88398bb9131f9fa8d63ab1e1500b4671e7a3c204a007b75908c431732772aa4eec0d7aafa20f

test:
  secret_key_base: 5957d6e98cbf317e9c212fe0c9e8f8da1a62f5d846e29fad097c34e50b21dbeb75b2e20f7c69379dd91054d08348e6d278e31d9e931b71f5bbdb73666b6bf995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
